### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by didierganthier** [didierganthier/javascript-group-capstone#21]
### Group capstone: set up your Kanban board
The Kanban board project has been set up and it can be found here: 
- https://github.com/didierganthier/javascript-group-capstone/projects/1

This project was created by @hopeforkoami and @didierganthier

**Comment by cynthiainga** [comment]
Hi @didierganthier & @hopeforkoami, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Required Changes ♻️

- [ ] Please cards should be assigned to team members, and also decide who is `Student A`, and `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students) 🙃 😉.
- [ ] And all cards with `group task` in the title should be assigned to someone (it does not matter to whom as students had freedom with that) 😁 😁.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShoiraTa** [comment]
## **STATUS: APPROVED  🟢 ** 
------
### Hi team, 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

### Highlights:
 ✔️ kanban board is setup correctly


Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![image](https://user-images.githubusercontent.com/77038610/192113752-c316f323-e076-4961-85fa-20b64eb8b6ed.png)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@shoirata] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
